version: "3.8"

services:
  mongodb:
    image: mongo:4.4.2
    container_name: mongodb
    restart: always
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_DB=${MONGO_DB}
    command: mongod --port 27018
    ports:
      - 27018:27018
    volumes:
      - ./docker_scripts/init_mongo_user.sh/:/docker-entrypoint-initdb.d/init_mongo_user.sh
      - mongodb:/data/db

  api:
    container_name: api
    build:
      context: ./
      dockerfile: ./Dockerfile
    command: bash -c "uvicorn app.main:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    env_file:
      - .env
    environment:
      - MONGO_DB=${MONGO_DB}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_PORT=${MONGO_PORT}

volumes:
  mongodb: