name: FastAPI CI

on: [push]

env:
  FAIL_LEVEL: WARNING
  ENV_TYPE: pipenv

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4

    services:
      mongodb:
        image: mongo:4.4.2
        env:
          MONGO_USER: test_user
          MONGO_PASSWORD: password
          MONGO_DB: chicago_incidents_test
          MONGO_HOST: localhost
        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install Dependencies
        run: |
          pip install pipenv
          pipenv install --dev
      - name: Run Tests
        run: |
          pipenv run pytest app --cov=./ --cov-report=xml
      - name: Upload Coverage Report
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage.xml
          flags: unittests
          fail_ci_if_error: true
