name: FastAPI CI

on: [push]

env:
  FAIL_LEVEL: WARNING
  ENV_TYPE: pipenv
  MONGO_USER: test_user
  MONGO_PASSWORD: password
  MONGO_DB: chicago_incidents_test
  MONGO_HOST: localhost

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.7, 3.8, 3.9 ]
      max-parallel: 4

    steps:
      - uses: actions/checkout@v2
      - name: Set up MongoDB
        run: |
          cd .github/helper_files
          docker-compose up --build -d mongodb
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          pip install pipenv
          pipenv install --dev
      - name: Run Tests
        run: |
          pipenv run pytest app --cov=./ --cov-report=xml
      - name: Upload Coverage Report
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage.xml
          flags: unittests
          fail_ci_if_error: true
